### ISSUE TITLE
! (x === y) → x !== y

### ISSUE THREAD

**Issue by maximal** [Rioran/rioran-clock#1]
https://github.com/Rioran/rioran-clock/blob/1afd7cf8c1e4a5bb4bb26b6e4001bdec80ea046e/js/scripts.js#L6

**Comment by maximal** [comment]
cash → cache

**Comment by Rioran** [comment]
Refactored, thanks! https://github.com/Rioran/rioran-clock/commit/cf934a9d448b77a916e36108dcd5e54efe771768#diff-60d1c73f64a9165c32e0c42d3a3a6bec1dcc4a466fa5136ddfbe217bbb58d418
